[tool.ruff]
line-length = 100
target-version = "py310" 
select = ["E", "F", "W", "B"]  # Enable most standard rules, including Bugbear rules
ignore = ["E501"]  # Ignore line length violations 

[tool.ruff.lint]
per-file-ignores = {
    "**/tests/*": ["E402"],  # Ignore import order issues in test files
    "**/config/*": ["E226"]  # Ignore "too many inline comments" in config files
} 