name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest pytest-cov pytest-asyncio pytest-mock httpx
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install mypy types-Flask types-requests
        
    - name: Lint with ruff
      continue-on-error: true
      run: |
        ruff check src/ tests/ --output-format=github
        ruff format src/ tests/ --check
        
    - name: Type check with mypy
      continue-on-error: true
      run: |
        mypy src/ --ignore-missing-imports --exclude="src/scraper/"
        
    - name: Run tests with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        TESTING: "true"
      run: |
        pytest --cov=src --cov-report=xml --cov-report=term-missing tests/ -v
        
    - name: Upload coverage to Codecov
      if: ${{ secrets.CODECOV_TOKEN != '' }}
      continue-on-error: true
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false
        files: ./coverage.xml
        flags: unittests

  security:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.12"
        
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        
    - name: Run Bandit
      run: bandit -r src/
      
    - name: Run Safety Check
      continue-on-error: true
      run: safety check