name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    services:
      milvus:
        image: milvusdb/milvus:v2.4.12-standalone@sha256:0c9a3a0d27d8b223f86c4c0f2f4aa4d3b3d0e8c7e3f5b2f4e4b4b4b4b4b4b4b
        env:
          ETCD_ENDPOINTS: localhost:2379
          MINIO_ADDRESS: localhost:9000
        ports:
          - 19530:19530
          - 9091:9091
        options: >-
          --health-cmd "sleep 60"
          --health-interval 30s
          --health-timeout 20s
          --health-retries 3
      
      minio:
        image: bitnami/minio:2024@sha256:1a9a98fad68227fbf9c64d66c6d4f0b6a6937568a8dff16f6267c6e8f850b8f5
        ports:
          - 9000:9000
        env:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
          MINIO_DEFAULT_BUCKETS: "mybucket:public"
        options: >-
          --health-cmd "sleep 10"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Pull Docker images
      run: |
        for i in {1..3}; do
          docker pull milvusdb/milvus:v2.4.12-standalone && break || sleep 15
        done
        for i in {1..3}; do
          docker pull bitnami/minio:2024 && break || sleep 15
        done
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest pytest-cov pytest-asyncio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .
        
    - name: Type check with mypy
      run: |
        pip install mypy types-all
        mypy src/
        
    - name: Run tests with pytest
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MILVUS_HOST: localhost
        MILVUS_PORT: 19530
      run: |
        pytest --cov=src tests/ --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install security tools
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
        
    - name: Run Bandit
      run: bandit -r src/
      
    - name: Run Safety Check
      run: safety check